openapi: 3.0.0
info:
  title: Product Service API
  description: API documentation for the Product Service using AWS Lambda
  version: 1.0.0

servers:
  - url: https://nzikyizgn4.execute-api.us-east-2.amazonaws.com/dev/
    description: AWS API Gateway URL

paths:
  /products:
    get:
      summary: Get all products
      description: Returns a list of all available products.
      responses:
        '200':
          description: A JSON array of product objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /products/{productId}:
    get:
      summary: Get product by ID
      description: Returns a single product based on the provided ID.
      parameters:
        - name: productId
          in: path
          required: true
          description: Unique identifier for the product
          schema:
            type: string
      responses:
        '200':
          description: A single product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: Unique product identifier
        title:
          type: string
          description: Name of the product
        description:
          type: string
          description: Short description of the product
        price:
          type: number
          format: float
          description: Price of the product
